sudo: required
language: python

services:
  - docker

before_install:

# env:
#   global:
#     - DOCKER_IMAGE=jmezna/rso-image-catalog:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER  
# before_install:
#     - docker-compose up   -d
#     - docker ps


# script:
#     - docker-compose run django python manage.py test polls
before_install:
  - docker-compose up -d --build
script:
  - docker-compose exec upload pytest "app/tests" -p no:warnings

after_script:
  - docker rm -f app  