version: '3.7'

services:
  upload:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - 8081:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATA_CATALOG_URL=http://data-catalog:5000
      - DATA_STORAGE_URL=http://data-storage:5000
      - HEALTH_DEMO_STATUS=True 
    networks:
      - backend
networks:
  backend:
    external: true
  