version: '3.7'

services:
  upload:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:dispatcher
    ports:
      - 8081:5000
    env_file:
      - ./.env.prod
